#cloud-config
users: # Collection von Benutzern
  - name: ubuntu # Der Benutzername des ersten Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo Regeln für diesen Benutzer
    groups: users, admin # Benutzer "ubuntu" wird den Gruppen "users" und "admin" hinzugefügt.
    home: /home/ubuntu # Das Heimatverzeichnis des Benutzers "ubuntu" wird auf "/home/ubuntu" festgelegt.
    shell: /bin/bash # Die Standard-Shell des Benutzers "ubuntu" wird auf "/bin/bash" gesetzt.
    ssh_authorized_keys: # Der öffentliche SSH-Schlüssel für den Benutzer "ubuntu" wird festgelegt.
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
ssh_pwauth: false # Die Passwort-SSH-Authentifizierung wird deaktiviert.
disable_root: false # Die Deaktivierung des Root-Benutzers wird nicht aktiviert.
package_update: true # Das System soll nach der Initialisierung Paketaktualisierungen durchführen.
packages: # Die Pakete "curl" und "wget" sollen installiert werden.
  - curl 
  - wget 
